#!/usr/bin/env node

/**
 * Codegen script: reads the generated token list JSON files and produces
 * TypeScript source files that embed the data with full type information.
 */

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..", "..");
const SRC = join(__dirname, "..", "src");
const CJS_DIR = join(__dirname, "..", "dist", "cjs");

mkdirSync(SRC, { recursive: true });
mkdirSync(CJS_DIR, { recursive: true });

// Generate mainnet.ts

const mainnetJson = readFileSync(
  join(ROOT, "tokenlist-mainnet.json"),
  "utf-8",
);

let mainnetData;
try {
  mainnetData = JSON.parse(mainnetJson);
} catch (err) {
  console.error("codegen: tokenlist-mainnet.json is not valid JSON:", err.message);
  process.exit(1);
}

writeFileSync(
  join(SRC, "mainnet.ts"),
  [
    "// Auto-generated by codegen.mjs -- do not edit",
    'import type { MainnetTokenList } from "./types.js";',
    "",
    `export const mainnetTokenList = ${mainnetJson.trimEnd()} as const satisfies MainnetTokenList;`,
    "",
  ].join("\n"),
);

// Generate testnet.ts

const testnetJson = readFileSync(
  join(ROOT, "tokenlist-testnet.json"),
  "utf-8",
);

try {
  JSON.parse(testnetJson);
} catch (err) {
  console.error("codegen: tokenlist-testnet.json is not valid JSON:", err.message);
  process.exit(1);
}

writeFileSync(
  join(SRC, "testnet.ts"),
  [
    "// Auto-generated by codegen.mjs -- do not edit",
    'import type { TestnetTokenList } from "./types.js";',
    "",
    `export const testnetTokenList = ${testnetJson.trimEnd()} as const satisfies TestnetTokenList;`,
    "",
  ].join("\n"),
);

// Generate index.ts (barrel re-export)

writeFileSync(
  join(SRC, "index.ts"),
  [
    "// Auto-generated by codegen.mjs -- do not edit",
    'export { mainnetTokenList } from "./mainnet.js";',
    'export { testnetTokenList } from "./testnet.js";',
    "export type {",
    "  Address,",
    "  MonadMainnetChainId,",
    "  MonadTestnetChainId,",
    "  MonadChainId,",
    "  CrossChainId,",
    "  BridgeProtocol,",
    "  CrossChainAddressEntry,",
    "  CrossChainAddresses,",
    "  BridgeInfo,",
    "  TokenExtensions,",
    "  Token,",
    "  MainnetToken,",
    "  TestnetToken,",
    "  Version,",
    "  TokenList,",
    "  MainnetTokenList,",
    "  TestnetTokenList,",
    '} from "./types.js";',
    "",
  ].join("\n"),
);

// Generate dist/cjs/package.json (CommonJS marker)

writeFileSync(
  join(CJS_DIR, "package.json"),
  `${JSON.stringify({ type: "commonjs" }, null, 2)}\n`,
);

// Sync package.json versions from the token list

const NPM_DIR = join(__dirname, "..");
const { major, minor, patch } = mainnetData.version;
const version = `${major}.${minor}.${patch}`;

const pkgPath = join(NPM_DIR, "package.json");
const pkg = JSON.parse(readFileSync(pkgPath, "utf-8"));
pkg.version = version;
writeFileSync(pkgPath, `${JSON.stringify(pkg, null, 2)}\n`);

console.log(
  `codegen: wrote src/mainnet.ts, src/testnet.ts, src/index.ts, dist/cjs/package.json, package.json (v${version})`,
);
